### ISSUE TITLE
Empty output Csv files /Labelling the tree

### ISSUE THREAD

**Issue by Sanyukta2002** [chrisruis/MutTui#14]
Hello @chrisruis , @gtonkinhill , @stevenweaver 
For my output CSV files : all_included double substitutions , all included mutations, all mutation counts , Iam getting empty tables with just the headers? Is this cause I did not label the tree?

First I assigned nodes to my tree with this :
`python3 add_tree_node_labels.py -t sarscov2_npl_tree.nwk -o nodetree.nwk`
This gave me an output tree with added nodes. 
Next, I assigned branch labels:
`python3 branch_labelling.py -t nodetree.nwk -o labelledtree.nwk`

However, this branch labelling script did not give me any output.

Why are my CSV files empty and why am i not getting output tree with branch labelling? Also, how do i generate the mutation plots pdfs  with my CSV file data ? Thank you

**Comment by chrisruis** [comment]
Hi @Sanyukta2001 MutTui is now run using a single MutTui command rather than the individual scripts. So to calculate a spectrum you'd use "MutTui run", to add node labels you'd use "MutTui label-nodes" and to label the tree you'd use "MutTui label-tree". You don't need to label the tree to run though, if you don't specify a labelled tree, MutTui will assign all mutations to a single spectrum.

More info in the docs at https://chrisruis.github.io/MutTui/#/
